- hosts: localhost
  connection: local

  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "sjleenobreak/jenkins-ansible:latest"
      state: started
      ports:
      - "80:8080"
